'use strict';
/**
 * DNS manager: BIND9 zones hosted on this server.
 * Zone files live in /var/lib/bind/; one generated include file declares all
 * panel zones to BIND. Every zone change is validated with named-checkzone
 * BEFORE the resolver reloads - invalid changes are rolled back automatically.
 */
const express = require('express');
const fs = require('fs');
const fsp = fs.promises;
const path = require('path');
const os = require('os');
const config = require('../config');
const db = require('./db');
const { run } = require('./exec');

const router = express.Router();

const ZONES_DIR = '/var/lib/bind';
const CONF_DIR = '/etc/bind';
const INCLUDE_FILE = path.join(CONF_DIR, 'named.conf.letzcontrol');
const MAIN_CONF = path.join(CONF_DIR, 'named.conf.local');
const TYPES = ['A', 'AAAA', 'CNAME', 'MX', 'NS', 'TXT', 'CAA'];

const DOMAIN_RE = /^(?=.{1,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/i;
const NAME_RE = /^(@|[a-z0-9_]([a-z0-9_-]*[a-z0-9_])?(\.[a-z0-9_-]+)*)$/i;
const HOST_RE = /^([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}\.?$/i;
const IPV4_RE = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/;

/* ------------------------------- helpers ------------------------------- */

/** Public IP used for default A records and shown in the NS instructions. */
function serverIp() {
  if (config.publicIp) return config.publicIp;
  const ifs = os.networkInterfaces();
  for (const names of Object.keys(ifs)) {
    for (const i of ifs[names] || []) {
      if (i.family === 'IPv4' && !i.internal) return i.address;
    }
  }
  return '127.0.0.1';
}

const zonePath = (domain) => path.join(ZONES_DIR, `${domain}.zone`);

function bindAvailable() {
  return run('command -v named-checkzone && command -v named || command -v named-checkzone');
}

async function serial(zone) {
  zone.lastSerial = Math.max(Math.floor(Date.now() / 1000), (zone.lastSerial || 0) + 1);
  db.save();
  return zone.lastSerial;
}

/** Render a zone's file content from the db record. */
function zoneFile(zone) {
  const s = zone.lastSerial || 1;
  let out = `$TTL 3600\n`;
  out += `@ IN SOA ns1.${zone.domain}. hostmaster.${zone.domain}. (\n`;
  out += `    ${s} ; serial\n    3600 ; refresh\n    900 ; retry\n    1209600 ; expire\n    3600 ) ; negative cache TTL\n\n`;
  for (const r of zone.records) {
    const name = r.name || '@';
    let line = `${name}  ${r.ttl || 3600}  IN  ${r.type}`;
    if (r.type === 'MX') line += `  ${r.priority || 10}  ${r.value}`;
    else if (r.type === 'TXT') {
      // TXT character-strings max 255 bytes - split long values (DKIM keys)
      // into chunks; resolvers concatenate them transparently.
      const s = String(r.value);
      const chunks = [];
      for (let i = 0; i < s.length; i += 255) {
        chunks.push(`"${s.slice(i, i + 255).replace(/"/g, '\\"')}"`);
      }
      line += '  ' + chunks.join(' ');
    } else line += `  ${r.value}`;
    out += line + '\n';
  }
  return out;
}

/** (Re)write the include file declaring every panel zone. */
async function writeInclude() {
  let out = '# Generated by letzControl - do not edit\n';
  for (const z of db.all('zones')) {
    out += `zone "${z.domain}" {\n    type master;\n    file "${zonePath(z.domain)}";\n    allow-transfer { none; };\n};\n\n`;
  }
  await fsp.mkdir(ZONES_DIR, { recursive: true });
  await fsp.writeFile(INCLUDE_FILE, out, { mode: 0o644 });
  let local = '';
  try { local = await fsp.readFile(MAIN_CONF, 'utf8'); } catch { local = ''; }
  if (!local.includes(INCLUDE_FILE)) {
    local += `\n# letzControl DNS zones\ninclude "${INCLUDE_FILE}";\n`;
    await fsp.writeFile(MAIN_CONF, local, { mode: 0o644 });
  }
}

/**
 * Write the zone file and validate it. On validation failure the previous
 * file content is restored and { ok:false, output } is returned, so BIND
 * never reloads a broken zone.
 */
async function writeAndCheck(zone) {
  const file = zonePath(zone.domain);
  const prev = await fsp.readFile(file).catch(() => null);
  await fsp.writeFile(file, zoneFile(zone), { mode: 0o644 });
  const chk = await run(`named-checkzone ${zone.domain} ${file}`);
  if (chk.ok) return { ok: true };
  if (prev !== null) await fsp.writeFile(file, prev, { mode: 0o644 });
  else await fsp.rm(file, { force: true });
  return { ok: false, output: (chk.stdout + chk.stderr).trim() };
}

async function reloadBind() {
  return run('systemctl reload named 2>/dev/null || systemctl reload bind9 2>/dev/null || rndc reload 2>/dev/null || systemctl restart named');
}

/** Validate a record body; returns { error } or { record }. */
function validateRecord(b) {
  const type = String(b.type || '').toUpperCase();
  if (!TYPES.includes(type)) return { error: `Type must be one of: ${TYPES.join(', ')}` };

  const name = String(b.name || '@').trim().toLowerCase();
  if (!NAME_RE.test(name)) return { error: 'Name must be @ or a subdomain like www / mail (a-z, 0-9, -, _)' };

  const value = String(b.value || '').trim();
  if (!value) return { error: 'Value is required' };
  if (/[\r\n]/.test(value)) return { error: 'Value must be a single line' };

  const ttl = b.ttl === undefined || b.ttl === '' ? 3600 : parseInt(b.ttl, 10);
  if (!Number.isFinite(ttl) || ttl < 60 || ttl > 86400) return { error: 'TTL must be 60-86400 seconds' };

  const rec = { type, name, value, ttl };

  // Hostname-based values must be absolute - BIND appends the origin to
  // values without a trailing dot, which would silently mangle them.
  const abs = (v) => (v.endsWith('.') ? v : v + '.');

  if (type === 'A') {
    const m = value.match(IPV4_RE);
    if (!m || m.slice(1).some((o) => +o > 255)) return { error: 'A record value must be a valid IPv4 address' };
  } else if (type === 'AAAA') {
    if (!/^[0-9a-f:.]+$/i.test(value) || !value.includes(':')) return { error: 'AAAA record value must be a valid IPv6 address' };
  } else if (type === 'CNAME' || type === 'NS') {
    if (value === '@' || !HOST_RE.test(value)) return { error: `${type} value must be a hostname (e.g. example.com)` };
    rec.value = abs(value);
  } else if (type === 'MX') {
    if (!HOST_RE.test(value)) return { error: 'MX value must be a mail host (e.g. mail.example.com)' };
    const p = b.priority === undefined || b.priority === '' ? 10 : parseInt(b.priority, 10);
    if (!Number.isFinite(p) || p < 0 || p > 65535) return { error: 'MX priority must be 0-65535' };
    rec.priority = p;
    rec.value = abs(value);
  } else if (type === 'TXT') {
    if (value.length > 4096) return { error: 'TXT value must be 4096 characters or less' };
  } else if (type === 'CAA') {
    if (!/^\d{1,3}\s+(issue|issuewild|iodef)\s+\S/.test(value)) {
      return { error: 'CAA value must look like: 0 issue "letsencrypt.org"' };
    }
  }
  return { record: rec };
}

function canAccess(req, zone) {
  if (req.user.role === 'admin' || zone.ownerId === req.user.id) return true;
  /* Zone of a website you own - follows the site's owner, and zones created
   * before siteId existed are matched by domain. */
  if (zone.siteId) {
    const site = db.get('sites', zone.siteId);
    if (site) return site.ownerId === req.user.id;
  }
  return !!db.findOne('sites', (s) => s.ownerId === req.user.id && s.domain === zone.domain);
}

/* ------------------------------- routes ------------------------------- */

router.use(async (_req, res, next) => {
  const avail = await bindAvailable();
  if (!avail.ok) {
    return res.status(503).json({ error: 'BIND9 is not installed - add it in the Setup Wizard first' });
  }
  next();
});

router.get('/zones', (req, res) => {
  const zones = db.find('zones', (z) => canAccess(req, z));
  const known = new Set(db.all('zones').map((z) => z.domain));
  const sites = (req.user.role === 'admin' ? db.all('sites') : db.find('sites', (s) => s.ownerId === req.user.id))
    .filter((s) => !known.has(s.domain));
  res.json({
    zones: zones.map((z) => {
      const owner = db.get('users', z.ownerId);
      return { ...z, owner: owner ? owner.username : '?' };
    }),
    availableSites: sites.map((s) => s.domain),
    serverIp: serverIp()
  });
});

router.post('/zones', async (req, res) => {
  const domain = String((req.body || {}).domain || '').toLowerCase().trim();
  if (!DOMAIN_RE.test(domain)) return res.status(400).json({ error: 'Invalid domain name' });
  if (db.findOne('zones', (z) => z.domain === domain)) {
    return res.status(409).json({ error: 'A zone for this domain already exists' });
  }
  const site = db.findOne('sites', (s) => s.domain === domain);
  if (req.user.role !== 'admin' && (!site || site.ownerId !== req.user.id)) {
    return res.status(403).json({ error: 'You can only create DNS zones for your own websites' });
  }
  const ip = serverIp();
  const zone = db.insert('zones', {
    domain,
    ownerId: req.user.id,
    ...(site ? { siteId: site.id } : {}),
    lastSerial: 0,
    records: [
      { type: 'NS', name: '@', value: `ns1.${domain}.`, ttl: 3600 },
      { type: 'A', name: 'ns1', value: ip, ttl: 3600 },
      { type: 'A', name: '@', value: ip, ttl: 3600 },
      { type: 'A', name: 'www', value: ip, ttl: 3600 }
    ]
  });
  await serial(zone);
  const chk = await writeAndCheck(zone);
  if (!chk.ok) {
    db.remove('zones', zone.id);
    return res.status(500).json({ error: `Zone rejected by named-checkzone:\n${chk.output}` });
  }
  await writeInclude();
  const rl = await reloadBind();
  res.status(201).json({ zone, reloadOk: rl.ok, serverIp: ip });
});

router.delete('/zones/:id', async (req, res) => {
  const zone = db.get('zones', req.params.id);
  if (!zone) return res.status(404).json({ error: 'Zone not found' });
  if (!canAccess(req, zone)) return res.status(403).json({ error: 'Not your zone' });
  db.remove('zones', zone.id);
  await fsp.rm(zonePath(zone.domain), { force: true });
  await writeInclude();
  const rl = await reloadBind();
  res.json({ ok: true, reloadOk: rl.ok });
});

router.post('/zones/:id/records', async (req, res) => {
  const zone = db.get('zones', req.params.id);
  if (!zone) return res.status(404).json({ error: 'Zone not found' });
  if (!canAccess(req, zone)) return res.status(403).json({ error: 'Not your zone' });

  const v = validateRecord(req.body || {});
  if (v.error) return res.status(400).json({ error: v.error });

  const before = JSON.stringify(zone.records);
  zone.records.push({ ...v.record, id: db.data.meta.nextRecId = (db.data.meta.nextRecId || 1000) + 1 });
  db.save();
  await serial(zone);

  const chk = await writeAndCheck(zone);
  if (!chk.ok) {
    zone.records = JSON.parse(before);
    db.save();
    await writeAndCheck(zone);
    return res.status(400).json({ error: `Record rejected by named-checkzone:\n${chk.output}` });
  }
  const rl = await reloadBind();
  res.json({ zone, reloadOk: rl.ok });
});

router.put('/zones/:id/records/:recId', async (req, res) => {
  const zone = db.get('zones', req.params.id);
  if (!zone) return res.status(404).json({ error: 'Zone not found' });
  if (!canAccess(req, zone)) return res.status(403).json({ error: 'Not your zone' });
  const idx = zone.records.findIndex((r) => r.id === req.params.recId);
  if (idx === -1) return res.status(404).json({ error: 'Record not found' });

  const v = validateRecord(req.body || {});
  if (v.error) return res.status(400).json({ error: v.error });

  const before = JSON.stringify(zone.records);
  zone.records[idx] = { ...v.record, id: zone.records[idx].id };
  db.save();
  await serial(zone);

  const chk = await writeAndCheck(zone);
  if (!chk.ok) {
    zone.records = JSON.parse(before);
    db.save();
    await writeAndCheck(zone);
    return res.status(400).json({ error: `Record rejected by named-checkzone:\n${chk.output}` });
  }
  const rl = await reloadBind();
  res.json({ zone, reloadOk: rl.ok });
});

router.delete('/zones/:id/records/:recId', async (req, res) => {
  const zone = db.get('zones', req.params.id);
  if (!zone) return res.status(404).json({ error: 'Zone not found' });
  if (!canAccess(req, zone)) return res.status(403).json({ error: 'Not your zone' });
  const idx = zone.records.findIndex((r) => r.id === req.params.recId);
  if (idx === -1) return res.status(404).json({ error: 'Record not found' });

  const before = JSON.stringify(zone.records);
  zone.records.splice(idx, 1);
  db.save();
  await serial(zone);

  const chk = await writeAndCheck(zone);
  if (!chk.ok) {
    zone.records = JSON.parse(before);
    db.save();
    await writeAndCheck(zone);
    return res.status(400).json({ error: `Zone rejected by named-checkzone:\n${chk.output}` });
  }
  const rl = await reloadBind();
  res.json({ zone, reloadOk: rl.ok });
});

/**
 * Add several records to a zone (used by the Mail module for MX/SPF/DKIM
 * hints). Validates every record, skips duplicates, rolls back on a
 * named-checkzone failure. Returns { ok, added, skipped, error? }.
 */
async function addRecordsToZone(domain, records) {
  const zone = db.findOne('zones', (z) => z.domain === domain);
  if (!zone) return { ok: false, error: 'This panel does not host a DNS zone for that domain' };
  const added = [];
  const skipped = [];
  const before = JSON.stringify(zone.records);
  for (const r of records || []) {
    const v = validateRecord(r);
    if (v.error) { skipped.push(`${r.type || '?'} ${r.name || '@'}: ${v.error}`); continue; }
    const dup = zone.records.find((x) =>
      x.type === v.record.type && x.name === v.record.name && String(x.value) === String(v.record.value));
    if (dup) { skipped.push(`${v.record.type} ${v.record.name}: already present`); continue; }
    zone.records.push({ ...v.record, id: (db.data.meta.nextRecId = (db.data.meta.nextRecId || 1000) + 1) });
    added.push(v.record);
  }
  if (!added.length) return { ok: true, added, skipped, zone };
  await serial(zone);
  const chk = await writeAndCheck(zone);
  if (!chk.ok) {
    zone.records = JSON.parse(before);
    db.save();
    await writeAndCheck(zone);
    return { ok: false, error: `Zone rejected by named-checkzone:\n${chk.output}` };
  }
  await writeInclude();
  await reloadBind();
  return { ok: true, added, skipped, zone };
}

module.exports = { router, addRecordsToZone, serverIp };
